/*
 * Copyright (C) Volition, Inc. 1999.  All rights reserved.
 *
 * All source code herein is the property of Volition, Inc. You may not sell 
 * or otherwise commercially exploit the source or things you created based on the 
 * source.
 *
*/ 


#pragma once

enum
{
	HUD_LEAD_INDICATOR,
	HUD_ORIENTATION_TEE,
	HUD_HOSTILE_TRIANGLE,
	HUD_TARGET_TRIANGLE,
	HUD_MISSION_TIME,
	HUD_RETICLE_CIRCLE,
	HUD_THROTTLE_GAUGE,
	HUD_RADAR,
	HUD_TARGET_MONITOR,
	HUD_CENTER_RETICLE,
	HUD_TARGET_MONITOR_EXTRA_DATA,
	HUD_TARGET_SHIELD_ICON, // Full size icon
	HUD_PLAYER_SHIELD_ICON, // Full size icon
	HUD_ETS_GAUGE,
	HUD_AUTO_TARGET,
	HUD_AUTO_SPEED,
	HUD_WEAPONS_GAUGE,
	HUD_ESCORT_VIEW,
	HUD_DIRECTIVES_VIEW,
	HUD_THREAT_GAUGE,
	HUD_AFTERBURNER_ENERGY, // Afterburning arc
	HUD_WEAPONS_ENERGY,
	HUD_WEAPON_LINKING_GAUGE,
	HUD_TARGET_MINI_ICON, // Mini shield icon centre
	HUD_OFFSCREEN_INDICATOR,
	HUD_TALKING_HEAD,
	HUD_DAMAGE_GAUGE,
	HUD_MESSAGE_LINES,
	HUD_MISSILE_WARNING_ARROW,
	HUD_CMEASURE_GAUGE,
	HUD_OBJECTIVES_NOTIFY_GAUGE,
	HUD_WINGMEN_STATUS,
	HUD_OFFSCREEN_RANGE,
	HUD_KILLS_GAUGE,
	HUD_ATTACKING_TARGET_COUNT,
	HUD_TEXT_FLASH,
	HUD_MESSAGE_BOX,
	HUD_SUPPORT_GAUGE,
	HUD_LAG_GAUGE,
	NUM_HUD_GAUGES
};

